name: Release

on:
  release:
    types: [published]
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
        python -m pip install -e .[signals] -r requirements-dev.txt

    - name: Publish package
      run: |
        python setup.py sdist bdist_wheel
